"""Render a session as the 8-item replay report the S9 rubric asks for.

Usage:
    uv run python make_replay_report.py <session_id>

Writes to state/sessions/<session_id>/replay_report.md
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path


def _load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def _node_output(node_state: dict):
    """Normalise node.result.output which may be a dict or a JSON string."""
    res = (node_state or {}).get("result") or {}
    out = res.get("output")
    if isinstance(out, str):
        try:
            return json.loads(out)
        except json.JSONDecodeError:
            return {"text": out}
    return out or {}


def render(sid: str) -> str:
    sess_dir = Path("state/sessions") / sid
    if not sess_dir.exists():
        raise SystemExit(f"no such session: {sess_dir}")

    query = (sess_dir / "query.txt").read_text().strip()
    graph = _load(sess_dir / "graph.json") or {}
    nodes_dir = sess_dir / "nodes"
    node_files = sorted(nodes_dir.glob("n_*.json"))
    nodes = {p.stem: _load(p) or {} for p in node_files}

    # Cost via V9's by-agent endpoint
    cost = {}
    try:
        with urllib.request.urlopen(
            f"http://localhost:8109/v1/cost/by_agent?session={sid}", timeout=5
        ) as r:
            cost = json.loads(r.read())
    except Exception as e:
        cost = {"error": str(e)}

    # Find the browser node
    browser_node = next(
        (n for n in nodes.values() if n.get("skill") == "browser"),
        None,
    )
    formatter_node = next(
        (n for n in nodes.values() if n.get("skill") == "formatter"),
        None,
    )
    distiller_node = next(
        (n for n in nodes.values() if n.get("skill") == "distiller"),
        None,
    )

    browser_out = _node_output(browser_node) if browser_node else {}
    formatter_out = _node_output(formatter_node) if formatter_node else {}
    distiller_out = _node_output(distiller_node) if distiller_node else {}

    out: list[str] = []
    out.append(f"# Replay report — session `{sid}`")
    out.append("")
    out.append("> Generated by `make_replay_report.py`. Covers all 8 items in the")
    out.append("> S9 assignment rubric: goal, planner DAG, browser path, browser")
    out.append("> actions, page-state logs, extracted data, final comparison table,")
    out.append("> turn + cost summary.")
    out.append("")

    # 1. Original user goal
    out.append("## 1. Original user goal")
    out.append("")
    out.append("```")
    out.append(query)
    out.append("```")
    out.append("")

    # 2. Planner DAG
    out.append("## 2. Planner DAG")
    out.append("")
    edges = graph.get("links") or graph.get("edges") or []
    g_nodes = graph.get("nodes") or []
    out.append("Nodes (in execution order):")
    out.append("")
    out.append("| id | skill | status | elapsed |")
    out.append("|----|-------|--------|---------|")
    for n in g_nodes:
        nid = n.get("id", "")
        st = nodes.get(nid, {})
        out.append(
            f"| {nid} | {n.get('skill', st.get('skill', ''))}"
            f" | {st.get('status', n.get('status', ''))}"
            f" | {st.get('elapsed_seconds', '?')}s |"
        )
    out.append("")
    out.append("Edges:")
    out.append("")
    out.append("```")
    for e in edges:
        out.append(f"  {e.get('source', '?')} -> {e.get('target', '?')}")
    out.append("```")
    out.append("")

    # 3. Browser path chosen
    out.append("## 3. Browser path chosen")
    out.append("")
    if browser_out:
        path = browser_out.get("path", "?")
        out.append(f"**`{path}`** — the cascade landed on this layer (one of")
        out.append("`extract` / `deterministic` / `a11y` / `vision` / `gateway_blocked`).")
        out.append("")
        out.append(f"- start URL: `{browser_out.get('url', '?')}`")
        out.append(f"- final URL: `{browser_out.get('final_url', '?')}`")
        out.append(f"- turns: {browser_out.get('turns', '?')}")
    else:
        out.append("(no browser node in this session)")
    out.append("")

    # 4. Browser actions taken
    out.append("## 4. Browser actions taken")
    out.append("")
    actions = browser_out.get("actions") or []
    if actions:
        out.append(f"{len(actions)} turns. Each turn the agent read the a11y tree, sent it")
        out.append("to a cheap text LLM, picked an action, and the driver dispatched it via")
        out.append("Playwright.")
        out.append("")
        out.append("| turn | action | mark | outcome |")
        out.append("|------|--------|------|---------|")
        for a in actions:
            turn_n = a.get("turn", "?")
            for act in a.get("actions") or [a]:
                if isinstance(act, dict):
                    out.append(
                        f"| {turn_n} | {act.get('type', '?')}"
                        f" | {act.get('mark', '-')}"
                        f" | {a.get('outcome', '-')} |"
                    )
    else:
        out.append("(no actions logged)")
    out.append("")

    # 5. Screenshots / page-state logs
    out.append("## 5. Screenshots or page-state logs")
    out.append("")
    browser_artifacts = sess_dir / "browser"
    if browser_artifacts.exists():
        files = sorted(browser_artifacts.glob("*"))
        out.append(f"{len(files)} artifact(s) in `state/sessions/{sid}/browser/`:")
        out.append("")
        for f in files[:40]:
            out.append(f"- `{f.name}` ({f.stat().st_size} bytes)")
    else:
        out.append("No per-turn artifact directory was written for this session — that's")
        out.append("expected when the a11y path didn't require set-of-marks. The text")
        out.append("LLM acted on the a11y summary directly. Page-state evidence is")
        out.append(f"the `actions` log (§4) plus the final URL above.")
    out.append("")

    # 6. Extracted data
    out.append("## 6. Extracted data")
    out.append("")
    if distiller_out:
        out.append("Distiller output:")
        out.append("")
        out.append("```json")
        out.append(json.dumps(distiller_out, indent=2)[:2000])
        out.append("```")
    elif browser_out.get("content"):
        out.append("Raw extracted content (Browser node):")
        out.append("")
        out.append("```")
        out.append(str(browser_out.get("content"))[:1500])
        out.append("```")
    else:
        out.append("(no distiller output)")
    out.append("")

    # 7. Final comparison table
    out.append("## 7. Final comparison table (Formatter's answer)")
    out.append("")
    if formatter_out:
        txt = formatter_out.get("text") or formatter_out.get("output") or formatter_out
        out.append(str(txt))
    else:
        out.append("(no formatter output)")
    out.append("")

    # 8. Turn count + cost summary
    out.append("## 8. Turn count + cost summary")
    out.append("")
    out.append(f"- DAG nodes: **{len(g_nodes)}**")
    out.append(f"- Browser turns: **{browser_out.get('turns', '?')}**")
    out.append("")
    if "by_agent" in cost:
        out.append("Per-skill token spend (V9 `/v1/cost/by_agent`):")
        out.append("")
        out.append("| skill | calls | input | output |")
        out.append("|-------|-------|-------|--------|")
        for agent, ag in cost.get("by_agent", {}).items():
            out.append(
                f"| {agent} | {ag.get('calls', '?')}"
                f" | {ag.get('input_tokens', '?')}"
                f" | {ag.get('output_tokens', '?')} |"
            )
        out.append("")
        out.append(f"- **Total input tokens**: {cost.get('total_input_tokens', '?')}")
        out.append(f"- **Total output tokens**: {cost.get('total_output_tokens', '?')}")
    else:
        out.append(f"Cost ledger unavailable: `{cost.get('error', 'no data')}`")
    out.append("")

    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: make_replay_report.py <session_id>", file=sys.stderr)
        return 1
    sid = sys.argv[1]
    md = render(sid)
    out_path = Path("state/sessions") / sid / "replay_report.md"
    out_path.write_text(md)
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
